# src/brjarvis/contracts/verification.py — Canonical Verification & Effect Receipts for BR JARVIS
"""
Canonical Verification and Physical Effect Receipt contracts for BR JARVIS operating runtime.
Defines EffectReceipt, VerificationStatus, and VerificationResult.
"""
from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class VerificationStatus(str, Enum):
    """Status outcomes for state and effect verification."""
    SUCCESS_VERIFIED = "SUCCESS_VERIFIED"
    SUCCESS_UNVERIFIED = "SUCCESS_UNVERIFIED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"


class EffectReceipt(BaseModel):
    """The Authoritative Evidence Receipt generated by real-world tool execution."""
    receipt_id: str = Field(default_factory=lambda: f"rcpt-{uuid.uuid4().hex[:10]}")
    action_id: str = Field(..., description="Task action or tool invocation ID")
    execution_id: str = Field(default="", description="Turn execution ID")
    expected_effect: str = Field(..., description="Postcondition or state change intended")
    observed_effect: str = Field(..., description="Ground truth observed from OS/browser/API")
    verified: bool = Field(..., description="True if observed_effect satisfies expected_effect")
    evidence: str = Field(default="", description="Specific verifiable evidence (hash, path, status)")
    timestamp: float = Field(default_factory=time.time)
    source: str = Field(default="host_verifier", description="Verifier component: host, browser, git, process")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class VerificationResult(BaseModel):
    """Outcome of an action verification check."""
    verified: bool
    status: VerificationStatus = VerificationStatus.SUCCESS_VERIFIED
    evidence: str = ""
    details: str = ""
    error: Optional[str] = None
    receipt: Optional[EffectReceipt] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
