# reasoning/speculative.py — Canonical Speculative Execution Engine — BR JARVIS v41.0 (MARK XLI)
"""
Consolidated speculative execution system:

1. SpeculativeEngine  — fast regex/rule-based intent pattern matcher that short-circuits
   the full ReAct loop for high-confidence, low-latency tool dispatches.

2. SpeculativeExecutionEngine — draft-and-validate system that generates candidate tool
   steps ahead of LLM confirmation to overlap generation and execution latency.

Both classes are canonical here.  All other files import from this module.
"""

from __future__ import annotations

import logging
import re
import time
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel, Field

from brjarvis.core.runtime import get_runtime

logger = logging.getLogger("JARVIS.Speculative")


# ── Fast Rule-Based Intent Speculator ────────────────────────────────────────


class SpeculativeEngine:
    """
    Speculative fast-path classifier for high-frequency intent resolution.

    Evaluates user input against a table of regex rules and, on a confident
    match, returns a (tool_name, tool_args) tuple that the orchestrator can
    dispatch *immediately* without waiting for a full LLM generation pass.
    """

    def __init__(self) -> None:
        # High-confidence intent patterns mapped to direct tool calls.
        # Each tuple: (regex_pattern, tool_name, args_extractor_callable)
        self.speculative_rules: List[Tuple[str, str, Any]] = [
            (
                r"^(open|launch|start)\s+(chrome|brave|edge|notepad|calculator|cmd|powershell)$",
                "open_app",
                lambda m: {"app_name": m.group(2)},
            ),
            (
                r"^(search|google|find)\s+(?:for\s+)?(.+)$",
                "web_search",
                lambda m: {"query": m.group(2)},
            ),
            (
                r"^(list|show)\s+(desktop\s+)?windows$",
                "window_manager",
                lambda m: {"action": "list"},
            ),
            (
                r"^(check|show|get)\s+system\s+health$",
                "system_health",
                lambda m: {},
            ),
        ]

    def speculate_intent(self, user_input: str) -> Optional[Tuple[str, Dict[str, Any]]]:
        """
        Evaluate *user_input* against speculative rules.

        Returns ``(tool_name, tool_args)`` when a high-confidence match is
        found, otherwise returns ``None``.
        """
        if not user_input or not user_input.strip():
            return None

        clean_input = user_input.strip().lower()
        for pattern, tool_name, args_extractor in self.speculative_rules:
            match = re.search(pattern, clean_input, re.IGNORECASE)
            if match:
                try:
                    args = args_extractor(match)
                    logger.debug("Speculative fast-path matched: tool=%s", tool_name)
                    return tool_name, args
                except Exception as exc:
                    logger.debug("Suppressed speculative rule error: %s", exc)
        return None


# ── Draft-and-Validate Speculative Execution Engine ──────────────────────────


class SpeculativeDraftStep(BaseModel):
    """Structured speculative step payload generated by fast draft models."""

    step_index: int
    tool_name: str
    tool_args: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    draft_model: str = "fast-draft-local"
    created_at: float = Field(default_factory=time.time)


class SpeculativeExecutionEngine:
    """
    Speculative step generator and verifier accelerating ReAct tool dispatch.

    Generates *candidate* tool-call steps ahead of the primary model's
    confirmation, allowing the executor to overlap generation latency with
    pre-flight work.  Accepted drafts count as acceleration wins; rejected
    drafts are discarded with zero cost to correctness.
    """

    def __init__(self) -> None:
        self.runtime = get_runtime()
        self.runtime.container.register_instance(SpeculativeExecutionEngine, self)
        self._accepted_count = 0
        self._rejected_count = 0
        logger.info("⚡ SpeculativeExecutionEngine initialized")

    def generate_draft_step(
        self,
        goal: str,
        step_index: int,
        context_history: List[Dict[str, Any]],
    ) -> Optional[SpeculativeDraftStep]:
        """
        Synthesise a speculative draft tool call step using fast deterministic
        rules or lightweight models.  Returns ``None`` when no confident draft
        can be produced.
        """
        goal_lower = goal.lower()

        if "read" in goal_lower and "file" in goal_lower:
            match = re.search(r"([\w\\/\.\-]+\.(?:py|md|json|txt|js|ts))", goal)
            if match:
                return SpeculativeDraftStep(
                    step_index=step_index,
                    tool_name="view_file",
                    tool_args={"AbsolutePath": match.group(1)},
                    confidence=0.92,
                )

        if "search" in goal_lower or "find" in goal_lower:
            words = goal.split()
            query = words[-1] if len(words) > 1 else goal
            return SpeculativeDraftStep(
                step_index=step_index,
                tool_name="grep_search",
                tool_args={"Query": query, "SearchPath": "."},
                confidence=0.80,
            )

        return None

    def validate_and_merge(
        self,
        draft_step: SpeculativeDraftStep,
        actual_tool_name: str,
        actual_tool_args: Dict[str, Any],
    ) -> bool:
        """
        Validate whether the speculative draft step matches primary model
        intent.  Updates acceptance/rejection counters for telemetry.
        """
        is_valid = draft_step.tool_name == actual_tool_name and draft_step.tool_args == actual_tool_args

        if is_valid:
            self._accepted_count += 1
            logger.info(
                "✅ Speculative step ACCEPTED for tool '%s' (total=%d)",
                actual_tool_name,
                self._accepted_count,
            )
        else:
            self._rejected_count += 1
            logger.debug(
                "ℹ️ Speculative step REJECTED (draft=%s, actual=%s)",
                draft_step.tool_name,
                actual_tool_name,
            )

        return is_valid

    def get_metrics(self) -> Dict[str, Any]:
        """Return speculative acceptance-rate telemetry metrics."""
        total = self._accepted_count + self._rejected_count
        rate = (self._accepted_count / total * 100.0) if total > 0 else 0.0
        return {
            "accepted_count": self._accepted_count,
            "rejected_count": self._rejected_count,
            "acceptance_rate_percent": round(rate, 2),
        }


# ── Module-Level Singleton & Factory ─────────────────────────────────────────

_global_speculative_engine: Optional[SpeculativeExecutionEngine] = None


def get_speculative_engine() -> SpeculativeExecutionEngine:
    """Return the process-wide singleton SpeculativeExecutionEngine."""
    global _global_speculative_engine
    if _global_speculative_engine is None:
        _global_speculative_engine = SpeculativeExecutionEngine()
    return _global_speculative_engine


__all__ = [
    "SpeculativeEngine",
    "SpeculativeDraftStep",
    "SpeculativeExecutionEngine",
    "get_speculative_engine",
]
