# reasoning/speculative.py — Speculative Drafting & Execution Engine for BR JARVIS MK38
"""
Implements speculative drafting and parallel validation to accelerate tool step execution loops.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from brjarvis.core.runtime import get_runtime

logger = logging.getLogger("JARVIS.Speculative")


class SpeculativeDraftStep(BaseModel):
    """Structured speculative step payload generated by fast draft models."""

    step_index: int
    tool_name: str
    tool_args: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    draft_model: str = "fast-draft-local"
    created_at: float = Field(default_factory=time.time)


class SpeculativeExecutionEngine:
    """
    Speculative step generator and verifier accelerating ReAct tool dispatch.
    """

    def __init__(self):
        self.runtime = get_runtime()
        self.runtime.container.register_instance(SpeculativeExecutionEngine, self)
        self._accepted_count = 0
        self._rejected_count = 0
        logger.info("⚡ SpeculativeExecutionEngine initialized")

    def generate_draft_step(
        self,
        goal: str,
        step_index: int,
        context_history: List[Dict[str, Any]],
    ) -> Optional[SpeculativeDraftStep]:
        """
        Synthesize a speculative draft tool call step using fast deterministic rules or light models.
        """
        goal_lower = goal.lower()

        # Fast deterministic drafting for standard read/search goals
        if "read" in goal_lower and "file" in goal_lower:
            import re
            match = re.search(r"([\w\\/\.\-]+\.(?:py|md|json|txt|js|ts))", goal)
            if match:
                return SpeculativeDraftStep(
                    step_index=step_index,
                    tool_name="view_file",
                    tool_args={"AbsolutePath": match.group(1)},
                    confidence=0.92,
                )

        if "search" in goal_lower or "find" in goal_lower:
            words = goal.split()
            query = words[-1] if len(words) > 1 else goal
            return SpeculativeDraftStep(
                step_index=step_index,
                tool_name="grep_search",
                tool_args={"Query": query, "SearchPath": "."},
                confidence=0.80,
            )

        return None

    def validate_and_merge(
        self,
        draft_step: SpeculativeDraftStep,
        actual_tool_name: str,
        actual_tool_args: Dict[str, Any],
    ) -> bool:
        """
        Validate whether the speculative draft step matches primary model intent.
        """
        is_valid = (
            draft_step.tool_name == actual_tool_name
            and draft_step.tool_args == actual_tool_args
        )

        if is_valid:
            self._accepted_count += 1
            logger.info(f"✅ Speculative step ACCEPTED for tool '{actual_tool_name}' (Total Accepted: {self._accepted_count})")
        else:
            self._rejected_count += 1
            logger.debug(f"ℹ️ Speculative step REJECTED (Draft: {draft_step.tool_name}, Actual: {actual_tool_name})")

        return is_valid

    def get_metrics(self) -> Dict[str, Any]:
        """Return speculative acceptance rate telemetry metrics."""
        total = self._accepted_count + self._rejected_count
        rate = (self._accepted_count / total * 100.0) if total > 0 else 0.0
        return {
            "accepted_count": self._accepted_count,
            "rejected_count": self._rejected_count,
            "acceptance_rate_percent": round(rate, 2),
        }


_global_speculative_engine: Optional[SpeculativeExecutionEngine] = None


def get_speculative_engine() -> SpeculativeExecutionEngine:
    global _global_speculative_engine
    if _global_speculative_engine is None:
        _global_speculative_engine = SpeculativeExecutionEngine()
    return _global_speculative_engine
